export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA';
export const ADD_INCOME_ARRAY = 'ADD_INCOME_ARRAY';
export const DELETE_INCOME_ARRAY = 'DELETE_INCOME_ARRAY';
export const UPDATE_INCOME_ARRAY = 'UPDATE_INCOME_ARRAY';
export const EDIT_INCOME_ARRAY = 'EDIT_INCOME_ARRAY';
export const CLEAR_APPLICATION_DATA = 'CLEAR_APPLICATION_DATA';

export const SUBMIT_START = 'SUBMIT_START';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAIL = 'SUBMIT_FAIL';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
